name: 'Setup VHS and deps'
description: 'Install VHS, ttyd, font, build fuzzy.so, clone screenshot deps'
inputs:
  skip-build:
    description: 'Skip make build when cache hit'
    required: false
    default: 'false'
  skip-deps:
    description: 'Skip cloning deps when cache hit'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install VHS and ttyd
      run: |
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
        echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
        sudo apt-get update
        sudo apt-get install -y vhs ttyd
      shell: bash

    - name: Install JetBrainsMono Nerd Font
      run: |
        mkdir -p ~/.local/share/fonts
        curl -fsSL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz \
          | tar -xJf - -C ~/.local/share/fonts
        fc-cache -fv
      shell: bash

    - name: Build fuzzy.so
      if: inputs.skip-build != 'true'
      run: make build
      shell: bash

    - name: Clone nvim-web-devicons
      if: inputs.skip-deps != 'true'
      run: |
        mkdir -p deps
        git clone --depth 1 https://github.com/nvim-tree/nvim-web-devicons deps/nvim-web-devicons
      shell: bash

    - name: Clone kanagawa colorscheme
      if: inputs.skip-deps != 'true'
      run: |
        mkdir -p deps
        git clone --depth 1 https://github.com/rebelot/kanagawa.nvim deps/kanagawa.nvim
      shell: bash
